Repository m4rs-mt/ILGPU, pull requests merged in 2021-07, with the labels that each got.

#516 Fixed RadixSortProvider and ScanProvider test cases.
  Src/ILGPU.Algorithms.Tests/RadixSortExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/ScanExtensionTests.tt
Labels: bug

#512 Adapt CI for monorepo
  .github/workflows/ci.yml
  Src/.config/dotnet-tools.json
Labels: enhancement

#524 Removed obsolete properties and methods.
  Src/ILGPU/Backends/OpenCL/CLCompiledKernel.cs
  Src/ILGPU/Backends/PTX/PTXCompiledKernel.cs
  Src/ILGPU/Grid.cs
  Src/ILGPU/Group.cs
  Src/ILGPU/Interop.cs
  Src/ILGPU/Runtime/Cuda/CudaNativeMethods.cs
  Src/ILGPU/Runtime/CurrentAccelerator.cs
  Src/ILGPU/Runtime/KernelLoaders.tt
  Src/ILGPU/Runtime/OpenCL/CLKernel.cs
  Src/ILGPU/Runtime/PeerAccess.cs
Labels: enhancement

#521 Workflows: Push pre-release packages to separate feed
  .github/workflows/ci.yml
Labels: enhancement

#530 Selective builds on macOS, master and tags
  .github/workflows/ci.yml
Labels: enhancement

#520 Workflows: Create release on tag
  .github/workflows/ci.yml
Labels: enhancement

#535 Changes InvalidEntryPointIndexParameterOfWrongType to be more descriptive
  Src/ILGPU/Resources/ErrorMessages.Designer.cs
  Src/ILGPU/Resources/ErrorMessages.resx
Labels: enhancement

#537 Merged ILGPU Wiki into Docs folder.
  Docs/Accelerators-and-Streams.md
  Docs/Debugging-and-Profiling.md
  Docs/Dynamically-Specialized-Kernels.md
  Docs/Getting-Started.md
  Docs/Inside-ILGPU.md
  Docs/Kernels.md
  Docs/Math-Functions.md
  Docs/Memory-Buffers-and-Views.md
  Docs/ReadMe.md
  Docs/Shared-Memory.md
  Docs/Upgrade-v0.1.X-to-v0.2.X.md
  Docs/Upgrade-v0.3.X-to-v0.5.X.md
  Docs/Upgrade-v0.6.X-to-v0.7.X.md
  Docs/Upgrade-v0.7.X-to-v0.8.X.md
  Docs/Upgrade-v0.8.0-to-v0.8.1.md
  Docs/Upgrade-v0.8.X-to-v0.9.X.md
Labels: enhancement

#546 Added updated documentation for 0.10.1
  Docs/Accelerators-and-Streams.md
  Docs/Getting-Started.md
  Docs/Primer_00.md
  Docs/Primer_01.md
  Docs/Primer_02.md
  Docs/ReadMe.md
  Docs/Tutorial_01.md
  Docs/Tutorial_02.md
  Docs/Tutorial_03.md
  Docs/Tutorial_04.md
Labels: enhancement

#559 Fixed naming of available static field modes.
  Src/ILGPU/ContextProperties.cs
  Src/ILGPU/Frontend/CodeGenerator/CodeGenerator.cs
Labels: bug, enhancement

#561 Fixed Sample solution and invalid project references.
  Samples/AdjustableSharedMemory/AdjustableSharedMemory.csproj
  Samples/AdvancedAtomics/AdvancedAtomics.csproj
  Samples/AdvancedViews/AdvancedViews.csproj
  Samples/AlgorithmsCuBlas/AlgorithmsCuBlas.csproj
  Samples/AlgorithmsGroups/AlgorithmsGroups.csproj
  Samples/AlgorithmsInitialize/AlgorithmsInitialize.csproj
  Samples/AlgorithmsMath/AlgorithmsMath.csproj
  Samples/AlgorithmsRadixSort/AlgorithmsRadixSort.csproj
  Samples/AlgorithmsReduce/AlgorithmsReduce.csproj
  Samples/AlgorithmsScan/AlgorithmsScan.csproj
  Samples/AlgorithmsSequence/AlgorithmsSequence.csproj
  Samples/AlgorithmsTransform/AlgorithmsTransform.csproj
  Samples/AlgorithmsWarps/AlgorithmsWarps.csproj
  Samples/CustomIntrinsics/CustomIntrinsics.csproj
  Samples/DeviceInfo/DeviceInfo.csproj
  Samples/DynamicSharedMemory/DynamicSharedMemory.csproj
  Samples/Empty/Empty.csproj
  Samples/EmptyAlgorithms/EmptyAlgorithms.csproj
  Samples/ExplicitlyGroupedKernels/ExplicitlyGroupedKernels.csproj
  Samples/GenericKernel/GenericKernel.csproj
  Samples/GroupGridIndices/GroupGridIndices.csproj
  Samples/ILGPU.Samples.sln
  Samples/ImplicitlyGroupedKernels/ImplicitlyGroupedKernels.csproj
  Samples/IndexImplementation/IndexImplementation.csproj
  Samples/LowLevelKernelCompilation/LowLevelKernelCompilation.csproj
  Samples/Mandelbrot/Mandelbrot.csproj
  Samples/MatrixMultiply/MatrixMultiply.csproj
  Samples/PinnedMemoryCopy/PinnedMemoryCopy.csproj
  Samples/SharedMemory/SharedMemory.csproj
  Samples/SimpleAlloc/SimpleAlloc.csproj
  Samples/SimpleAtomics/SimpleAtomics.csproj
  Samples/SimpleConstants/SimpleConstants.csproj
  Samples/SimpleKernel/SimpleKernel.csproj
  Samples/SimpleMath/SimpleMath.csproj
  Samples/SimpleStructures/SimpleStructures.csproj
  Samples/SimpleViews/SimpleViews.csproj
  Samples/SpecializedKernel/SpecializedKernel.csproj
  Samples/WarpShuffle/WarpShuffle.csproj
Labels: bug

#563 Ported Simple samples to ILGPU v1.0.x.
  Samples/DeviceInfo/DeviceInfo.csproj
  Samples/DeviceInfo/Program.cs
  Samples/Empty/Empty.csproj
  Samples/Empty/Program.cs
  Samples/SimpleAlloc/Program.cs
  Samples/SimpleAlloc/SimpleAlloc.csproj
  Samples/SimpleAtomics/Program.cs
  Samples/SimpleAtomics/SimpleAtomics.csproj
  Samples/SimpleConstants/Program.cs
  Samples/SimpleConstants/SimpleConstants.csproj
  Samples/SimpleKernel/Program.cs
  Samples/SimpleKernel/SimpleKernel.csproj
  Samples/SimpleMath/Program.cs
  Samples/SimpleMath/SimpleMath.csproj
  Samples/SimpleStructures/Program.cs
  Samples/SimpleStructures/SimpleStructures.csproj
  Samples/SimpleViews/Program.cs
  Samples/SimpleViews/SimpleViews.csproj
Labels: enhancement

#564 Ported Algorithms samples to ILGPU v1.0.x.
  Samples/AlgorithmsCuBlas/AlgorithmsCuBlas.csproj
  Samples/AlgorithmsCuBlas/Program.cs
  Samples/AlgorithmsGroups/AlgorithmsGroups.csproj
  Samples/AlgorithmsGroups/Program.cs
  Samples/AlgorithmsInitialize/AlgorithmsInitialize.csproj
  Samples/AlgorithmsInitialize/Program.cs
  Samples/AlgorithmsMath/AlgorithmsMath.csproj
  Samples/AlgorithmsMath/Program.cs
  Samples/AlgorithmsRadixSort/AlgorithmsRadixSort.csproj
  Samples/AlgorithmsRadixSort/Program.cs
  Samples/AlgorithmsReduce/AlgorithmsReduce.csproj
  Samples/AlgorithmsReduce/Program.cs
  Samples/AlgorithmsScan/AlgorithmsScan.csproj
  Samples/AlgorithmsScan/Program.cs
  Samples/AlgorithmsSequence/AlgorithmsSequence.csproj
  Samples/AlgorithmsSequence/Program.cs
  Samples/AlgorithmsTransform/AlgorithmsTransform.csproj
  Samples/AlgorithmsTransform/Program.cs
  Samples/AlgorithmsWarps/AlgorithmsWarps.csproj
  Samples/AlgorithmsWarps/Program.cs
  Samples/EmptyAlgorithms/EmptyAlgorithms.csproj
  Samples/EmptyAlgorithms/Program.cs
Labels: enhancement

#565 Ported Applications samples to ILGPU v1.0.x.
  Samples/Mandelbrot/Mandelbrot.cs
  Samples/Mandelbrot/Mandelbrot.csproj
Labels: enhancement
