Repository m4rs-mt/ILGPU, pull requests merged in 2021-05, with the labels that each got.

#475 Fixed critical issue in raw-view length computations in Runtime MemoryBuffer classes.
  Src/ILGPU/Runtime/Cuda/CudaMemoryBuffer.cs
  Src/ILGPU/Runtime/OpenCL/CLMemoryBuffer.cs
Labels: bug

#482 Added stream profiling markers.
  Src/ILGPU.Tests/Configurations.txt
  Src/ILGPU.Tests/Generic/TestContext.cs
  Src/ILGPU.Tests/ILGPU.Tests.csproj
  Src/ILGPU.Tests/ProfilingMarkers.cs
  Src/ILGPU/Context.Builder.cs
  Src/ILGPU/ContextProperties.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.Designer.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.resx
  Src/ILGPU/Runtime/AcceleratorStream.cs
  Src/ILGPU/Runtime/CPU/CPUProfilingMarker.cs
  Src/ILGPU/Runtime/CPU/CPUStream.cs
  Src/ILGPU/Runtime/Cuda/CudaAPI.cs
  Src/ILGPU/Runtime/Cuda/CudaAPI.xml
  Src/ILGPU/Runtime/Cuda/CudaNativeMethods.cs
  Src/ILGPU/Runtime/Cuda/CudaProfilingMarker.cs
  Src/ILGPU/Runtime/Cuda/CudaStream.cs
  Src/ILGPU/Runtime/OpenCL/CLAPI.cs
  Src/ILGPU/Runtime/OpenCL/CLAPI.xml
  Src/ILGPU/Runtime/OpenCL/CLNativeMethods.cs
  Src/ILGPU/Runtime/OpenCL/CLProfilingMarker.cs
  Src/ILGPU/Runtime/OpenCL/CLStream.cs
  Src/ILGPU/Runtime/ProfilingMarker.cs
Labels: feature

#485 Avoid duplicate CI runs for pull requests made from the same repo
  .github/workflows/ci.yml
Labels: enhancement
