Repository m4rs-mt/ILGPU, pull requests merged in 2021-12, with the labels that each got.

#658 Adds Hgemm, which is gemm with ILGPU's Half type
  Src/ILGPU.Algorithms/Runtime/Cuda/CuBlasMappings.ttinclude
Labels: enhancement, feature

#647 DebugView Enhancements
  Src/ILGPU/Runtime/ArrayViews.tt
  Src/ILGPU/Runtime/DebugViews.cs
Labels: bug, enhancement, feature

#668 Improved automatic vectorization by enhancing the alignment analysis.
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Emitter.cs
  Src/ILGPU/IR/Analyses/PointerAlignments.cs
Labels: enhancement

#703 Refined LICM transformation to make code movement smarter.
  Src/ILGPU/IR/Transformations/LoopInvariantCodeMotion.cs
Labels: enhancement

#671 Added on-the-fly optimization for nested SetField operations.
  Src/ILGPU/IR/Construction/Structures.cs
Labels: enhancement

#710 Fixed warnings in .NET6 builds.
  Src/ILGPU.Algorithms/Runtime/Cuda/API/NvmlNativeMethods.tt
  Src/ILGPU/ContextProperties.cs
  Src/ILGPU/Frontend/Intrinsic/LanguageIntrinsics.cs
  Src/ILGPU/Static/DllImports.tt
Labels: enhancement

#717 add logo folder inside the docs folder
  Docs/logo/ai/ILGPU_IconLogo_RGB.ai
  Docs/logo/ai/ILGPU_SignatureLogo_RGB.ai
  Docs/logo/jpg/ILGPU_IconLogo_RGB-Black.jpg
  Docs/logo/jpg/ILGPU_IconLogo_RGB-Color.jpg
  Docs/logo/jpg/ILGPU_IconLogo_RGB-White.jpg
  Docs/logo/jpg/ILGPU_SignatureLogo_RGB-Black.jpg
  Docs/logo/jpg/ILGPU_SignatureLogo_RGB-Color.jpg
  Docs/logo/jpg/ILGPU_SignatureLogo_RGB-White.jpg
  Docs/logo/png/ILGPU_IconLogo_RGB-Black.png
  Docs/logo/png/ILGPU_IconLogo_RGB-Color.png
  Docs/logo/png/ILGPU_IconLogo_RGB-White.png
  Docs/logo/png/ILGPU_SignatureLogo_RGB-Black.png
  Docs/logo/png/ILGPU_SignatureLogo_RGB-Color.png
  Docs/logo/png/ILGPU_SignatureLogo_RGB-White.png
  Docs/logo/svg/ILGPU_IconLogo_RGB-Black.svg
  Docs/logo/svg/ILGPU_IconLogo_RGB-Color.svg
  Docs/logo/svg/ILGPU_IconLogo_RGB-White.svg
  Docs/logo/svg/ILGPU_SignatureLogo_RGB-Black.svg
  Docs/logo/svg/ILGPU_SignatureLogo_RGB-Color.svg
  Docs/logo/svg/ILGPU_SignatureLogo_RGB-White.svg
Labels: enhancement

#714 Prevent unintentional initialization of Accelerator.Current.
  Src/ILGPU/Context.cs
  Src/ILGPU/Runtime/CPU/CPUAccelerator.cs
  Src/ILGPU/Runtime/CPU/CPUDevice.cs
Labels: enhancement
