Repository m4rs-mt/ILGPU, pull requests merged in 2022-01, with the labels that each got.

#726 Fixed missing explicit binding of Cuda context for memcopy operations.
  Src/ILGPU/Runtime/Cuda/CudaMemoryBuffer.cs
Labels: bug

#727 Added missing struct constraint on TraversalSuccessorsProvider.
  Src/ILGPU/IR/Analyses/TraversalOrder.cs
  Src/ILGPU/IR/BasicBlockCollection.cs
Labels: enhancement

#729 Require .NET 6 for building and enable package validation
  .github/workflows/ci.yml
  README.md
  Samples/Directory.Build.props
  Src/Directory.Build.props
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/ILGPU.csproj
  global.json
Labels: enhancement, feature

#704 Added new global code placement transformation.
  Src/ILGPU/Backends/IL/ILBackend.cs
  Src/ILGPU/Backends/OpenCL/CLBackend.cs
  Src/ILGPU/Backends/PTX/PTXBackend.cs
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/IR/Analyses/Dominators.cs
  Src/ILGPU/IR/BasicBlock.cs
  Src/ILGPU/IR/BasicBlockCollection.cs
  Src/ILGPU/IR/Construction/BasicBlock.Builder.cs
  Src/ILGPU/IR/Transformations/CodePlacement.cs
  Src/ILGPU/IR/Transformations/DeadCodeElimination.cs
  Src/ILGPU/IR/Transformations/LoopInvariantCodeMotion.cs
  Src/ILGPU/IR/Transformations/Optimizer.cs
  Src/ILGPU/IR/Values/ArrayValues.cs
  Src/ILGPU/IR/Values/Debug.cs
  Src/ILGPU/IR/Values/IOValues.cs
  Src/ILGPU/IR/Values/Memory.cs
  Src/ILGPU/IR/Values/MethodCall.cs
  Src/ILGPU/IR/Values/SideEffectValue.cs
  Src/ILGPU/IR/Values/Threads.cs
  Src/ILGPU/IR/Values/Use.cs
Labels: feature

#730 Fixed exception handling when missing assembly binding redirect.
  Src/ILGPU/Frontend/ILFrontend.cs
  Src/ILGPU/IR/Construction/Method.Builder.cs
  Src/ILGPU/IR/IRContext.cs
  Src/ILGPU/IR/Transformations/Transformation.cs
  Src/ILGPU/Runtime/SpecializationCache.cs
Labels: enhancement

#733 Added automatic folding of Convert values into LEA values.
  Src/ILGPU/IR/Construction/Memory.cs
Labels: enhancement

#734 Significantly improved CodePlacement
  Src/ILGPU.Tests/BasicMovement.cs
  Src/ILGPU.Tests/Configurations.txt
  Src/ILGPU/IR/Analyses/Movement.cs
  Src/ILGPU/IR/Construction/Method.Builder.cs
  Src/ILGPU/IR/Transformations/CodePlacement.cs
  Src/ILGPU/IR/Values/Atomic.cs
  Src/ILGPU/IR/Values/Memory.cs
Labels: enhancement, feature

#739 Updated version to v1.1.0-beta2.
  Src/Directory.Build.props
Labels: enhancement

#741 Disabled AssemblyBuilder reloading in TestContext.
  Src/ILGPU.Tests/Generic/TestContext.cs
  Src/ILGPU/RuntimeSystem.cs
Labels: enhancement
