Repository m4rs-mt/ILGPU, pull requests merged in 2022-10, with the labels that each got.

#861 Fix small wiki error
  Docs/Shared-Memory.md
Labels: bug

#843 Features for allocating 2D/3D in shared memory
  Src/ILGPU.Tests/SharedMemory.cs
  Src/ILGPU/Memory.tt
Labels: enhancement

#866 Updated CI pipeline to use Github Environment Files.
  .github/workflows/ci.yml
  .github/workflows/runners.yaml
Labels: enhancement

#869 Fixed inlining of blocks with more than two successors.
  Src/ILGPU.Tests/BasicCalls.cs
  Src/ILGPU/IR/Transformations/Inliner.cs
Labels: bug

#865 Fixed retrieving kernel object from launchers with implicit stream.
  Src/ILGPU.Tests/Configurations.txt
  Src/ILGPU.Tests/GetKernelTests.cs
  Src/ILGPU/Runtime/Kernel.cs
Labels: bug, feature

#859 Update runners config with new AMI
  .github/workflows/runners/config.yaml
Labels: enhancement

#864 Add Octo Nudge workflow and Github action
  .github/workflows/nudge.yml
Labels: enhancement

#868 Restored CudaMemoryBuffer MemSet and CopyTo semantics from 1.0.
  Src/ILGPU/Runtime/Cuda/CudaMemoryBuffer.cs
Labels: bug
