Repository m4rs-mt/ILGPU, pull requests merged in 2022-04, with the labels that each got.

#760 Extended inline PTX to support multiple output and by-ref parameters.
  Samples/InlinePTXAssembly/Program.cs
  Src/ILGPU.Tests/LanguageTests.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Values.cs
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/Frontend/Intrinsic/LanguageIntrinsics.cs
  Src/ILGPU/IR/Construction/LanguageValues.cs
  Src/ILGPU/IR/Values/LanguageValues.cs
  Src/ILGPU/IR/Values/ValueKind.cs
  Src/ILGPU/Runtime/Cuda/CudaAsm.Generated.tt
  Src/ILGPU/Runtime/Cuda/CudaAsm.cs
Labels: enhancement, feature

#776 Reviewed ILGPU documentation.
  Docs/Debugging-and-Profiling.md
  Docs/Dynamically-Specialized-Kernels.md
  Docs/Inside-ILGPU.md
  Docs/Kernels.md
  Docs/Math-Functions.md
  Docs/Memory-Buffers-and-Views.md
  Docs/Primer_00.md
  Docs/Primer_01.md
  Docs/Primer_02.md
  Docs/ReadMe.md
  Docs/Shared-Memory.md
  Docs/Tutorial_01.md
  Docs/Tutorial_02.md
  Docs/Tutorial_03.md
  Docs/Tutorial_04.md
Labels: bug, enhancement

#765 Uniform branches for NVIDIA GPUs
  Src/ILGPU/Backends/PTX/PTXBackend.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Terminators.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Values.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.cs
  Src/ILGPU/Backends/PTX/PTXInstructions.Data.cs
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/IR/Analyses/FixPointAnalysis.cs
  Src/ILGPU/IR/Analyses/Uniforms.cs
Labels: enhancement, feature

#784 Fixed issues with LibDevice integration.
  Src/ILGPU/Backends/PTX/PTXLibDeviceMethods.tt
  Src/ILGPU/Backends/PTX/PTXLibDeviceNvvm.tt
  Src/ILGPU/Runtime/Cuda/LibDevice.tt
Labels: bug

#774 Fixed issue with unsigned nested conversions.
  Src/ILGPU.Tests/ConvertIntOperations.cs
  Src/ILGPU/IR/Construction/Convert.cs
Labels: bug

#783 Updated copyright year in GitHub workflow scripts.
  .github/workflows/Scripts/UpdateSampleReferences.ps1
Labels: enhancement

#770 Enable dynamic self-hosted CUDA runners
  .github/workflows/ci.yml
  .github/workflows/runners.yaml
  .github/workflows/runners/config.yaml
Labels: enhancement, github_actions

#779 Blazor Sample App
  Samples/BlazorSampleApp/App.razor
  Samples/BlazorSampleApp/BlazorSampleApp.csproj
  Samples/BlazorSampleApp/Components/BasicCanvas.razor
  Samples/BlazorSampleApp/Components/BasicCanvas.razor.cs
  Samples/BlazorSampleApp/Components/BasicCanvas.razor.css
  Samples/BlazorSampleApp/Components/BasicCanvasEnums.cs
  Samples/BlazorSampleApp/Components/BasicCanvasExtensions.cs
  Samples/BlazorSampleApp/Components/Tooltip.razor
  Samples/BlazorSampleApp/ILGPUWebHost/ComputeHost.cs
  Samples/BlazorSampleApp/ILGPUWebHost/ComputeHostExtension.cs
  Samples/BlazorSampleApp/ILGPUWebHost/ComputeSession.cs
  Samples/BlazorSampleApp/ILGPUWebHost/IComputeHost.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/IMandelbrotBasic.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/IMandelbrotClient.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotBasic.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotClient.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotExtensions.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageBasic.razor
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageBasic.razor.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageCPU.razor
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageCPU.razor.cs
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageStream.razor
  Samples/BlazorSampleApp/MandelbrotExplorer/MandelbrotPageStream.razor.cs
  Samples/BlazorSampleApp/Pages/Error.cshtml
  Samples/BlazorSampleApp/Pages/Error.cshtml.cs
  Samples/BlazorSampleApp/Pages/Index.razor
  Samples/BlazorSampleApp/Pages/_Host.cshtml
  Samples/BlazorSampleApp/Pages/_Layout.cshtml
  Samples/BlazorSampleApp/Program.cs
  Samples/BlazorSampleApp/Properties/launchSettings.json
  Samples/BlazorSampleApp/Shared/MainLayout.razor
  Samples/BlazorSampleApp/Shared/MainLayout.razor.css
  Samples/BlazorSampleApp/Shared/NavMenu.razor
  Samples/BlazorSampleApp/Shared/NavMenu.razor.css
  Samples/BlazorSampleApp/Shared/SurveyPrompt.razor
  Samples/BlazorSampleApp/_Imports.razor
  Samples/BlazorSampleApp/appsettings.Development.json
  Samples/BlazorSampleApp/appsettings.json
  Samples/BlazorSampleApp/wwwroot/Images/Mandelbrot.png
  Samples/BlazorSampleApp/wwwroot/Scripts/BasicCanvas.js
  Samples/BlazorSampleApp/wwwroot/css/bootstrap/bootstrap.min.css
  Samples/BlazorSampleApp/wwwroot/css/bootstrap/bootstrap.min.css.map
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/FONT-LICENSE
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/ICON-LICENSE
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/README.md
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/css/open-iconic-bootstrap.min.css
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/fonts/open-iconic.eot
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/fonts/open-iconic.otf
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/fonts/open-iconic.svg
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/fonts/open-iconic.ttf
  Samples/BlazorSampleApp/wwwroot/css/open-iconic/font/fonts/open-iconic.woff
  Samples/BlazorSampleApp/wwwroot/css/site.css
  Samples/BlazorSampleApp/wwwroot/favicon.ico
  Samples/ILGPU.Samples.sln
Labels: enhancement, feature
