Repository m4rs-mt/ILGPU, pull requests merged in 2023-07, with the labels that each got.

#1021 Adjusted project language versions to 11.
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU/ILGPU.csproj
Labels: enhancement

#1022 Extended RNG functionality.
  Src/ILGPU.Algorithms/CompatibilitySuppressions.xml
  Src/ILGPU.Algorithms/Random/IRandomProvider.cs
  Src/ILGPU.Algorithms/Random/RNG.cs
  Src/ILGPU.Algorithms/Random/RandomExtensions.cs
  Src/ILGPU.Algorithms/Random/ThreadWiseRNG.cs
  Src/ILGPU.Algorithms/Random/XorShift128.cs
  Src/ILGPU.Algorithms/Random/XorShift128Plus.cs
  Src/ILGPU.Algorithms/Random/XorShift32.cs
  Src/ILGPU.Algorithms/Random/XorShift64Star.cs
Labels: enhancement, feature

#1023 Added new Vector data types for .NET 7.
  .gitignore
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU.Algorithms/Vectors/IVectorType.cs
  Src/ILGPU.Algorithms/Vectors/VectorTypes.tt
  Src/ILGPU.Algorithms/Vectors/VectorView.cs
Labels: feature

#1027 Fixed generic static abstract methods
  Src/ILGPU.Algorithms.Tests/VectorTests.cs
  Src/ILGPU.Tests/Generic/TestBase.cs
  Src/ILGPU/Frontend/CodeGenerator/Calls.cs
Labels: bug

#1028 Added new generic optimization API
  Src/ILGPU.Algorithms/Optimization/BoundsView.cs
  Src/ILGPU.Algorithms/Optimization/IOptimizationFunction.cs
  Src/ILGPU.Algorithms/Optimization/IOptimizer.cs
  Src/ILGPU.Algorithms/Optimization/OptimizationEngine.cs
  Src/ILGPU.Algorithms/Optimization/OptimizationResult.cs
  Src/ILGPU.Algorithms/Optimization/Optimizer.cs
Labels: feature

#1032 Adjusted copyright headers for PR #1005.
  Samples/AlgorithmsMath/Program.cs
Labels: enhancement

#1005 Improved AlgorithmsMath sample readability
  Samples/AlgorithmsMath/Program.cs
Labels: enhancement

#1029 Added Particle-Swarm Optimizer
  Src/ILGPU.Algorithms.Tests/Configurations.txt
  Src/ILGPU.Algorithms.Tests/OptimizationTests.cs
  Src/ILGPU.Algorithms/Optimization/Optimizers/PSO.cs
  Src/ILGPU.Algorithms/Optimization/Optimizers/PSOptimizer.cs
  Src/ILGPU.Algorithms/Optimization/Optimizers/PSView.cs
Labels: feature

#924 Added new specialized sparse-matrix extensions.
  Src/ILGPU.Algorithms.Tests/Configurations.txt
  Src/ILGPU.Algorithms.Tests/MatrixTests.cs
  Src/ILGPU.Algorithms/ConcurrentStreamProcessor.cs
  Src/ILGPU.Algorithms/MatrixOperations/MaskedMatrixProcessor.cs
  Src/ILGPU.Algorithms/MatrixOperations/MaskedSparseMatrixExtensions.cs
  Src/ILGPU.Algorithms/MatrixOperations/SparseMatrixExtensions.cs
  Src/ILGPU.Algorithms/MatrixOperations/SparseMatrixShapeView.cs
  Src/ILGPU.Algorithms/MatrixOperations/SparseMatrixView.cs
Labels: feature
