Repository m4rs-mt/ILGPU, pull requests merged in 2023-08, with the labels that each got.

#1050 Added support for implicit bool to int casts.
  Src/ILGPU/Frontend/CodeGenerator/Arithmetic.cs
Labels: bug

#1045 Ignore unsucessful loads of debug symbols
  Src/ILGPU/Frontend/DebugInformation/DebugInformationManager.cs
Labels: bug

#1044 Added sample to demonstrate SparseMatrix extensions.
  Samples/AlgorithmsSparseMatrix/AlgorithmsSparseMatrix.csproj
  Samples/AlgorithmsSparseMatrix/Program.cs
  Samples/ILGPU.Samples.sln
Labels: enhancement

#1043 Added sample to demonstrate Optimization extensions.
  Samples/AlgorithmsOptimization/AlgorithmsOptimization.csproj
  Samples/AlgorithmsOptimization/Program.cs
  Samples/ILGPU.Samples.sln
Labels: enhancement

#1052 Updated version to v1.5.0-stable.
  Src/Directory.Build.props
Labels: versioning

#1053 Updated version to v2.0.0-beta1.
  Src/Directory.Build.props
  Src/ILGPU.Algorithms/CompatibilitySuppressions.xml
  Src/ILGPU/CompatibilitySuppressions.xml
Labels: versioning

#1035 Create MAINTAINERS.md
  MAINTAINERS.md
Labels: versioning

#1042 Collapsable Sidebar for Website
  Site/_includes/doc/extras-js.html
  Site/_includes/doc/sidebar.html
  Site/_layouts/doc.html
  Site/_sass/extras-styles.scss
  Site/_sass/sidebar-collapse.scss
  Site/assets/css/doc.scss
  Site/assets/js/sidebar-collapse.js
Labels: enhancement

#1036 Added new Span-specific extension methods.
  Src/ILGPU/Util/Spans.cs
Labels: feature

#1037 Added new Vector-specific extension methods.
  Src/ILGPU/Util/Vectors.cs
Labels: feature

#1033 Removed .NetFramework471, .NetStandard2.1, .NetCore3.1, and .Net5.0 builds
  .github/workflows/Scripts/FixNugetSymbolPackages.ps1
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  Samples/Directory.Build.props
  Src/Directory.Build.props
  Src/ILGPU.Algorithms.Tests/Generic/AlgorithmsTestBase.cs
  Src/ILGPU.Algorithms.Tests/XMathTests.BitOperations.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Log.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Pow.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Rcp.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Rem.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Round.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Sqrt.tt
  Src/ILGPU.Algorithms.Tests/XMathTests.Trig.tt
  Src/ILGPU.Algorithms/AlgorithmContextMappings.tt
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU.Algorithms/XMath/Round.cs
  Src/ILGPU.Tests/ILGPU.Tests.csproj
  Src/ILGPU.Tests/UnaryFloatOperations.cs
  Src/ILGPU.Tests/ValueTuples.tt
  Src/ILGPU/Frontend/Intrinsic/RemappedIntrinsics.Generated.tt
  Src/ILGPU/Frontend/Intrinsic/RemappedIntrinsics.cs
  Src/ILGPU/ILGPU.csproj
  Src/ILGPU/IndexTypes.tt
  Src/ILGPU/IntrinsicMath.CPUOnly.tt
  Src/ILGPU/IntrinsicMath.cs
  Src/ILGPU/Util/NativeLibrary.cs
  Src/ILGPU/Util/NullableAttributes.cs
Labels: bug, enhancement, .NET, github_actions, versioning

#1038 Random ranges
  .gitignore
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU.Algorithms/Random/RandomExtensions.cs
  Src/ILGPU.Algorithms/Random/RandomRanges.tt
  Src/ILGPU.Algorithms/Random/XorShift128.cs
  Src/ILGPU.Algorithms/Random/XorShift32.cs
Labels: feature

#1062 Exposed private members to other ILGPU classes
  Src/ILGPU/Interop.cs
  Src/ILGPU/RuntimeSystem.cs
Labels: enhancement

#1066 Pass WriteToOutput to backends
  Src/ILGPU/Backends/IBackendCodeGenerator.cs
  Src/ILGPU/Backends/OpenCL/CLCodeGenerator.Values.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Values.cs
Labels: enhancement
