Repository m4rs-mt/ILGPU, pull requests merged in 2023-03, with the labels that each got.

#954 Fixed reinterpret cast of Half on OpenCL.
  Src/ILGPU/Backends/OpenCL/CLCodeGenerator.Values.cs
  Src/ILGPU/Backends/OpenCL/CLInstructions.Data.cs
Labels: bug

#955 Fixed failing unit tests when run in DEBUG configuration.
  Src/ILGPU.Tests/KernelEntryPoints.cs
Labels: enhancement

#950 Fixed comments in PinnedMemoryCopy sample.
  Samples/PinnedMemoryCopy/Program.cs
Labels: enhancement

#951 Removed obsolete code in RuntimeSystem.
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/RuntimeAPI.cs
  Src/ILGPU/RuntimeSystem.cs
Labels: enhancement

#958 Updated Cuda tool for website design changes.
  Tools/CudaVersionUpdateTool/Services/ParserService.cs
  Tools/CudaVersionUpdateTool/Util/Runner.cs
Labels: enhancement

#962 Fixed status checks on protected branches.
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-site.yml
Labels: bug

#946 Enabled P/Invoke source generation with LibraryImport.
  Src/ILGPU.Algorithms/CompatibilitySuppressions.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuBlasAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuBlasNativeMethods.tt
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuRandAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuRandAPI.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuRandNativeMethods.tt
  Src/ILGPU.Algorithms/Runtime/Cuda/API/NvmlAPI.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/CuBlasEnums.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/CuBlasMappings.ttinclude
  Src/ILGPU.Algorithms/Runtime/Cuda/CuRand.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/CuRandEnums.cs
  Src/ILGPU/Runtime/Cuda/CudaAPI.xml
  Src/ILGPU/Runtime/OpenCL/CLAPI.xml
  Src/ILGPU/Static/DllImporter.ttinclude
  Src/ILGPU/Static/DllImports.tt
  Src/ILGPU/Static/DllLibraryImporter.ttinclude
Labels: feature

#967 Fixed setup of CI matrix.
  .github/workflows/ci.yml
Labels: bug

#949 Added MemoryBufferStrides sample project.
  Samples/ILGPU.Samples.sln
  Samples/MemoryBufferStrides/AssemblyAttributes.cs
  Samples/MemoryBufferStrides/MemoryBufferStrides.csproj
  Samples/MemoryBufferStrides/Program.cs
Labels: enhancement

#966 Ensure kernel parameters are blittable types.
  Src/ILGPU.Tests/KernelEntryPoints.cs
  Src/ILGPU/Backends/EntryPoints/ArgumentMapper.cs
  Src/ILGPU/IR/Types/TypeInformationManager.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.Designer.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.resx
Labels: enhancement

#970 Added sample project for Static Abstract Interface Members.
  Samples/ILGPU.Samples.sln
  Samples/StaticAbstractInterfaceMembers/Program.cs
  Samples/StaticAbstractInterfaceMembers/StaticAbstractInterfaceMembers.csproj
Labels: enhancement, feature

#973 Bump runners version to 2.303.0
  .github/workflows/runners/config.yaml
Labels: enhancement

#974 Updated Cuda Library API versions.
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuBlasNativeMethods.tt
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuFFTAPI.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuFFTWAPI.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuRandAPI.xml
  Src/ILGPU.Algorithms/Runtime/Cuda/API/NvJpegAPI.xml
Labels: enhancement

#975 Added support for LibDevice using Cuda Release v12.
  Src/ILGPU/Backends/PTX/PTXBackend.cs
  Src/ILGPU/Backends/PTX/PTXLibDeviceNvvm.tt
Labels: enhancement
