Repository m4rs-mt/ILGPU, pull requests merged in 2023-09, with the labels that each got.

#1077 Removed obsolete pre-processor code.
  Samples/AlgorithmsSparseMatrix/Program.cs
  Samples/Mandelbrot/Program.cs
  Samples/PinnedMemoryCopy/Program.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuBlasAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuFFTAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuFFTWAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/CuRandAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/NvJpegAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/API/NvmlAPI.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/CuBlasException.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/CuFFTException.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/CuRandException.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/NvJpegException.cs
  Src/ILGPU.Algorithms/Runtime/Cuda/NvmlException.cs
  Src/ILGPU.Algorithms/XMath/Rem.cs
  Src/ILGPU.Tests/PageLockedMemory.cs
  Src/ILGPU.Tests/UnaryFloatOperations.cs
  Src/ILGPU/Backends/Backend.cs
  Src/ILGPU/Backends/PhiBindings.cs
  Src/ILGPU/Frontend/Intrinsic/LanguageIntrinsics.cs
  Src/ILGPU/Runtime/ArrayViewExtensions.cs
  Src/ILGPU/Runtime/Cuda/CudaException.cs
  Src/ILGPU/Runtime/Cuda/NvvmAPI.cs
  Src/ILGPU/Runtime/OpenCL/CLException.cs
  Src/ILGPU/Runtime/PageLockedArrays.cs
  Src/ILGPU/Util/NativeLibrary.cs
Labels: enhancement

#1074 Common FP16 Capability
  Src/ILGPU.Tests/CompareFloatOperations.tt
  Src/ILGPU.Tests/ConvertFloatOperations.tt
  Src/ILGPU.Tests/ConvertIntOperations.Generated.tt
  Src/ILGPU.Tests/FixedBuffers.tt
  Src/ILGPU.Tests/Generic/TestData.cs
  Src/ILGPU.Tests/GridOperations.cs
  Src/ILGPU.Tests/GroupOperations.cs
  Src/ILGPU.Tests/ReinterpretCasts.tt
  Src/ILGPU.Tests/SharedMemory.cs
  Src/ILGPU.Tests/UnaryFloatOperations.cs
  Src/ILGPU.Tests/WarpOperations.cs
  Src/ILGPU/Runtime/CPU/CPUDevice.cs
  Src/ILGPU/Static/Capabilities.xml
  Src/ILGPU/Static/CapabilitiesImporter.ttinclude
  Src/ILGPU/Static/CapabilityContext.tt
Labels: enhancement

#1069 Added simplification of IfBranch terminators.
  Src/ILGPU/IR/Construction/Terminators.cs
Labels: enhancement

#1073 Made tests group-capability aware
  Src/ILGPU.Tests/GroupOperations.cs
  Src/ILGPU.Tests/KernelEntryPoints.cs
  Src/ILGPU.Tests/MemoryBufferOperations.tt
Labels: enhancement

#1070 Simplified loop processing of IR-based loops.
  Src/ILGPU/IR/Analyses/LoopInfo.cs
  Src/ILGPU/IR/Analyses/Loops.cs
  Src/ILGPU/IR/Transformations/LoopInvariantCodeMotion.cs
  Src/ILGPU/IR/Transformations/LoopUnrolling.cs
Labels: enhancement

#1079 Fixed BasicValueType getter of PaddingType.
  Src/ILGPU/IR/Types/PaddingType.cs
Labels: bug

#1071 Extended support for ternary operations
  Src/ILGPU/IntrinsicMath.CPUOnly.tt
  Src/ILGPU/Static/ArithmeticEnums.tt
  Src/ILGPU/Static/TernaryMathOperations.xml
Labels: enhancement

#1072 Extended Type information
  Src/ILGPU/Static/TypeInformation.ttinclude
Labels: enhancement, feature

#1068 Type node extensions
  Src/ILGPU/IR/Types/ArrayType.cs
  Src/ILGPU/IR/Types/HandleType.cs
  Src/ILGPU/IR/Types/PaddingType.cs
  Src/ILGPU/IR/Types/PointerTypes.cs
  Src/ILGPU/IR/Types/PrimitiveTypes.cs
  Src/ILGPU/IR/Types/StructureType.cs
  Src/ILGPU/IR/Types/TypeNode.cs
  Src/ILGPU/IR/Types/VoidType.cs
  Src/ILGPU/Util/TypeExtensions.cs
Labels: enhancement, feature

#1061 Enhanced comments and fixed typos.
  Src/ILGPU/Backends/Backend.cs
  Src/ILGPU/Backends/EntryPoints/EntryPoint.cs
  Src/ILGPU/Backends/IL/DefaultILBackend.cs
  Src/ILGPU/Backends/PTX/PTXArgumentMapper.cs
  Src/ILGPU/Runtime/CPU/CPURuntimeContext.cs
  Src/ILGPU/Runtime/Device.cs
  Src/ILGPU/Runtime/KernelLauncherBuilder.cs
Labels: enhancement

#1060 Added .vscode directory to .gitignore file.
  .gitignore
Labels: enhancement

#1059 Added new ParallelCache and ParallelProcessingCache classes
  Src/ILGPU/Util/ParallelCache.cs
Labels: enhancement, feature

#1046 Create "All required checks succeeded" check run when "All required checks done" CI job is actually successful
  .github/workflows/check-required.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-site.yml
Labels: enhancement

#1065 Refined PTX argument mapping and analyses
  Src/ILGPU/Backends/EntryPoints/ArgumentMapper.cs
  Src/ILGPU/Backends/PTX/Analyses/DefaultPTXBlockSchedule.cs
  Src/ILGPU/Backends/PTX/Analyses/OptimizedPTXBlockSchedule.cs
  Src/ILGPU/Backends/PTX/Analyses/PTXBlockSchedule.cs
  Src/ILGPU/Backends/PTX/PTXArgumentMapper.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.cs
  Src/ILGPU/Backends/PTX/Transformations/PTXBlockScheduling.cs
Labels: enhancement

#1064 Updated PhiBindings analysis
  Src/ILGPU/Backends/OpenCL/CLCodeGenerator.cs
  Src/ILGPU/Backends/PTX/Analyses/PTXBlockSchedule.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.cs
  Src/ILGPU/Backends/PhiBindings.cs
Labels: enhancement

#1083 Extended test execution to accept custom KernelSpecialization instances.
  Src/ILGPU.Tests/Generic/TestBase.cs
Labels: enhancement

#1067 Refined IL emitters
  Src/ILGPU/Backends/IL/ILEmitter.cs
  Src/ILGPU/Backends/IL/ILEmitterExtensions.cs
  Src/ILGPU/Backends/IL/Transformations/ILAcceleratorSpecializer.cs
Labels: enhancement, feature

#1063 Refined Atomics
  Src/ILGPU/AtomicFunctions.tt
  Src/ILGPU/Backends/OpenCL/CLIntrinsics.cs
  Src/ILGPU/Backends/PTX/PTXIntrinsics.cs
Labels: enhancement

#1081 Fixed IfConversion
  Src/ILGPU.Tests/BasicJumps.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.Terminators.cs
  Src/ILGPU/Backends/PTX/PTXCodeGenerator.cs
  Src/ILGPU/Backends/PhiBindings.cs
  Src/ILGPU/IR/Transformations/IfConversion.cs
Labels: bug

#1084 Modified OpenCL generator to forward declare all variables.
  Src/ILGPU/Backends/OpenCL/CLCodeGenerator.Emitter.cs
  Src/ILGPU/Backends/OpenCL/CLCodeGenerator.cs
  Src/ILGPU/Backends/OpenCL/CLFunctionGenerator.cs
  Src/ILGPU/Backends/OpenCL/CLKernelFunctionGenerator.cs
Labels: bug

#1087 Updated version to v1.5.1-beta1.
  Src/Directory.Build.props
  Src/ILGPU.Algorithms/CompatibilitySuppressions.xml
  Src/ILGPU/CompatibilitySuppressions.xml
Labels: enhancement

#1055 Velocity SIMD CPU Runtime (Runtime + Scalar x2)
  .github/workflows/ci.yml
  .gitignore
  Src/ILGPU.Tests.Velocity/.editorconfig
  Src/ILGPU.Tests.Velocity/Configurations.tt
  Src/ILGPU.Tests.Velocity/ILGPU.Tests.Velocity.csproj
  Src/ILGPU.Tests.Velocity/TestContext.cs
  Src/ILGPU.sln
  Src/ILGPU/Backends/Backend.cs
  Src/ILGPU/Backends/Velocity/Analyses/VelocityMasks.cs
  Src/ILGPU/Backends/Velocity/Scalar/Scalar.cs
  Src/ILGPU/Backends/Velocity/Scalar/ScalarOperations.tt
  Src/ILGPU/Backends/Velocity/Scalar/ScalarTypeGenerator.cs
  Src/ILGPU/Backends/Velocity/Transformations/VelocityBlockScheduling.cs
  Src/ILGPU/Backends/Velocity/VelocityArgumentMapper.cs
  Src/ILGPU/Backends/Velocity/VelocityBackend.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.IO.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.Terminators.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.Threads.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.Values.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.Views.cs
  Src/ILGPU/Backends/Velocity/VelocityCodeGenerator.cs
  Src/ILGPU/Backends/Velocity/VelocityCompiledKernel.cs
  Src/ILGPU/Backends/Velocity/VelocityFunctionGenerator.cs
  Src/ILGPU/Backends/Velocity/VelocityGenerationModule.cs
  Src/ILGPU/Backends/Velocity/VelocityHelpers.cs
  Src/ILGPU/Backends/Velocity/VelocityKernelFunctionGenerator.cs
  Src/ILGPU/Backends/Velocity/VelocityOperations.ttinclude
  Src/ILGPU/Backends/Velocity/VelocityTargetSpecializer.cs
  Src/ILGPU/Backends/Velocity/VelocityTypeGenerator.cs
  Src/ILGPU/ILGPU.csproj
  Src/ILGPU/IR/Analyses/Loops.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.Designer.cs
  Src/ILGPU/Resources/RuntimeErrorMessages.resx
  Src/ILGPU/Runtime/Accelerator.cs
  Src/ILGPU/Runtime/CPU/CPUAccelerator.cs
  Src/ILGPU/Runtime/CPU/CPUMemoryBuffer.cs
  Src/ILGPU/Runtime/IAcceleratorExtensionProvider.cs
  Src/ILGPU/Runtime/Velocity/VelocityAccelerator.cs
  Src/ILGPU/Runtime/Velocity/VelocityContextExtensions.cs
  Src/ILGPU/Runtime/Velocity/VelocityDevice.cs
  Src/ILGPU/Runtime/Velocity/VelocityEntryPointHandler.cs
  Src/ILGPU/Runtime/Velocity/VelocityGroupExecutionContext.cs
  Src/ILGPU/Runtime/Velocity/VelocityKernel.cs
  Src/ILGPU/Runtime/Velocity/VelocityMemoryBuffer.cs
  Src/ILGPU/Runtime/Velocity/VelocityParameters.cs
  Src/ILGPU/Runtime/Velocity/VelocityProfilingMarker.cs
  Src/ILGPU/Runtime/Velocity/VelocityStream.cs
  Src/ILGPU/Static/Capabilities.xml
  Src/ILGPU/Static/CapabilitiesImporter.ttinclude
  Src/ILGPU/Static/CapabilityContext.tt
  Src/ILGPU/Static/TypeInformation.ttinclude
  Src/ILGPU/Static/UnaryMathOperations.xml
Labels: feature
