Repository m4rs-mt/ILGPU, pull requests merged in 2024-04, with the labels that each got.

#1175 Bump Microsoft.CodeAnalysis.CSharp from 4.8.0 to 4.9.2
  Src/ILGPU.Analyzers.Tests/ILGPU.Analyzers.Tests.csproj
  Src/ILGPU.Analyzers/ILGPU.Analyzers.csproj
Labels: enhancement

#1180 Fixed missing assertions in sample code.
  Samples/SimpleDebugAssert/Program.cs
Labels: bug

#1181 Fixed missing IO operations in sample code.
  Samples/SimpleWriteLine/Program.cs
Labels: bug

#1182 Fixed OpenCL printf newline output.
  Src/ILGPU/IR/Values/IOValues.cs
Labels: bug

#1185 Moved OpenCL IntrinsicMath implementations.
  Src/ILGPU.Algorithms/CL/CLContext.Generated.tt
  Src/ILGPU.Algorithms/CL/CLContext.cs
  Src/ILGPU.Algorithms/CL/CLMath.cs
  Src/ILGPU/Backends/OpenCL/CLIntrinsics.cs
  Src/ILGPU/IntrinsicMath.BinaryLog.cs
Labels: enhancement, feature

#1186 Added Tools to CI pipeline.
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: enhancement

#1176 Fixed alignment when marshalling Cuda kernel parameters.
  Src/ILGPU.Tests/KernelEntryPoints.cs
  Src/ILGPU/IR/Types/IRTypeContext.cs
  Src/ILGPU/IR/Types/StructureType.cs
Labels: bug

#1187 Updated NVVM to support Cuda SDK v8.
  Src/ILGPU/Context.Builder.cs
  Src/ILGPU/Runtime/Cuda/NvvmAPI.cs
Labels: bug

#1177 Added DLL resolver for Cuda on WSL.
  Src/ILGPU/Runtime/Cuda/CudaContextExtensions.cs
Labels: enhancement, feature

#1210 Update 05_Dynamically-Specialized-Kernels.md
  Docs/03_Advanced/05_Dynamically-Specialized-Kernels.md
Labels: bug

#1195 Updated version to v1.5.2-beta1.
  LICENSE.txt
  README.md
  Src/Directory.Build.props
  Src/ILGPU.Algorithms/Properties/ILGPU.Algorithms.nuspec.targets
  Src/ILGPU/CompatibilitySuppressions.xml
  Src/ILGPU/Properties/ILGPU.nuspec.targets
Labels: enhancement
