Repository m4rs-mt/ILGPU, pull requests merged in 2024-02, with the labels that each got.

#1154 Fixed regression from environment variables with CodeQL pipeline.
  .github/workflows/codeql-analysis.yml
Labels: bug

#1160 Bump actions/upload-artifact and download-artifact from 3 to 4
  .github/workflows/ci.yml
Labels: enhancement

#1161 Bump unit test nuget packages.
  Src/ILGPU.Algorithms.Tests.CPU/ILGPU.Algorithms.Tests.CPU.csproj
  Src/ILGPU.Algorithms.Tests.Cuda/ILGPU.Algorithms.Tests.Cuda.csproj
  Src/ILGPU.Algorithms.Tests.OpenCL/ILGPU.Algorithms.Tests.OpenCL.csproj
  Src/ILGPU.Algorithms.Tests/ArrayExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/GroupExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/ILGPU.Algorithms.Tests.csproj
  Src/ILGPU.Algorithms.Tests/InitializeTests.cs
  Src/ILGPU.Algorithms.Tests/MatrixTests.cs
  Src/ILGPU.Algorithms.Tests/OptimizationTests.cs
  Src/ILGPU.Algorithms.Tests/RadixSortExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/RandomTests.tt
  Src/ILGPU.Algorithms.Tests/ReductionExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/ReorderExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/ScanExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/SequencerTests.tt
  Src/ILGPU.Algorithms.Tests/TransformerExtensionTests.tt
  Src/ILGPU.Algorithms.Tests/VectorTests.cs
  Src/ILGPU.Algorithms.Tests/WarpExtensionTests.tt
  Src/ILGPU.Analyzers.Tests/ILGPU.Analyzers.Tests.csproj
  Src/ILGPU.Analyzers.Tests/InterleaveFields.cs
  Src/ILGPU.Analyzers.Tests/Snapshots/InterleaveFields.NestedNamespaceClassNotPartial.verified.txt
  Src/ILGPU.Analyzers.Tests/Snapshots/InterleaveFields.SimpleNotPartial.verified.txt
  Src/ILGPU.Analyzers/ILGPU.Analyzers.csproj
  Src/ILGPU.Tests.CPU/ILGPU.Tests.CPU.csproj
  Src/ILGPU.Tests.Cuda/ILGPU.Tests.Cuda.csproj
  Src/ILGPU.Tests.OpenCL/ILGPU.Tests.OpenCL.csproj
  Src/ILGPU.Tests.Velocity/ILGPU.Tests.Velocity.csproj
  Src/ILGPU.Tests/ArrayViews.cs
  Src/ILGPU.Tests/CompareFloatOperations.tt
  Src/ILGPU.Tests/ILGPU.Tests.csproj
  Src/ILGPU.Tests/PageLockedMemory.cs
  Src/ILGPU.Tests/UnaryFloatOperations.cs
Labels: enhancement

#1112 add ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement

#1114 add ISSUE_TEMPLATE/ask_question.yml
  .github/ISSUE_TEMPLATE/help_request.yml
Labels: enhancement

#1166 Fix assert exception in kernel entry points.
  Src/ILGPU.Tests/KernelEntryPoints.cs
Labels: enhancement

#1162 Added fixed-precision numbers using Int32 and Int64 base types.
  .gitignore
  Src/ILGPU.Algorithms/FixedPrecision/FixedIntConfig.ttinclude
  Src/ILGPU.Algorithms/FixedPrecision/FixedInts.tt
  Src/ILGPU.Algorithms/ILGPU.Algorithms.csproj
  Src/ILGPU.Algorithms/Random/RandomExtensions.cs
  Src/ILGPU.Algorithms/Random/RandomRanges.tt
  Src/ILGPU.Algorithms/Vectors/VectorTypes.tt
Labels: feature
